pipeline:
  build:
    image: registry.airwallex.com/alpine-curl
    pull: true
    commands:
      - printenv
      - echo "nihao"
      - sleep 10
      - echo "hola"
      - echo "double kill"
      - cat a
      - cat b
    #when:
      #event: [pull_request]
  trigger-pr:
    image: registry.airwallex.com/alpine-curl
    pull: true
    commands:
      - printenv
      - echo "nihao"
      - sleep 10
      - echo "hola"
      - echo "double kill"
      - cat a
      - cat b
      - echo "$${TOKEN}"
      - curl -s "https://api.github.com/repos/${CI_REPO_NAME}/pulls?access_token=$${TOKEN}" | jq -r '.[].head.ref'  | grep ${DRONE_BRANCH} > /dev/null 2>&1  && trigger=1 || trigger=0
      - echo "trigger is $${trigger}"
    secrets: [ token ]
