pipeline:
  build:
    image: registry.airwallex.com/alpine-curl
    commands:
      - printenv
      - echo "nihao"
      - sleep 10
      - echo "hola"
      - echo "double kill"
      - cat a
      - cat b
    #when:
      #event: [pull_request]
  trigger-pr:
    image: registry.airwallex.com/alpine-curl
    commands:
      - printenv
      - echo "nihao"
      - sleep 10
      - echo "hola"
      - echo "double kill"
      - cat a
      - cat b
      - echo $${TEST}
      - echo $${test}
