pipeline:
  build:
    image: ubuntu
    commands:
      - echo "nihao"
      - sleep 10
      - echo "hola"
    when:
      event: [pull_request]

  trigger-jenkins:
    when:
      branch:
        - develop
        - feature/*
        - feature/jenkins_integ
      event: [push]
    image: registry.airwallex.com/alpine-curl:latest
    pull: true
    commands:
      - printenv
      - echo ${DRONE_BRANCH} | grep two123 > /dev/null 2>&1 && echo "this is develop branch" && exit 0 || exit 0
      - sh trigger.sh
