pipeline:
  build:
    image: ubuntu
    commands:
      - printenv
      - echo "nihao"
      - sleep 10
      - echo "hola"
      - echo "double kill"
      - cat a
      - cat b
    when:
      event: [pull_request]
